// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqliteDao

import (
	"time"
)

type Category struct {
	ID        int64      `db:"id" json:"id"`
	Name      string     `db:"name" json:"name"`
	Desc      string     `db:"desc" json:"desc"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
	UpdatedAt *time.Time `db:"updated_at" json:"updated_at"`
}

type Detail struct {
	ID     int64  `db:"id" json:"id"`
	Desc   string `db:"desc" json:"desc"`
	ImgUrl string `db:"img_url" json:"img_url"`
	TodoID int64  `db:"todo_id" json:"todo_id"`
}

type Group struct {
	ID        int64      `db:"id" json:"id"`
	Name      string     `db:"name" json:"name"`
	Desc      string     `db:"desc" json:"desc"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
	UpdatedAt *time.Time `db:"updated_at" json:"updated_at"`
}

type Post struct {
	ID          int64      `db:"id" json:"id"`
	Name        string     `db:"name" json:"name"`
	CreatedAt   *time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   *time.Time `db:"updated_at" json:"updated_at"`
	CreatedByID string     `db:"created_by_id" json:"created_by_id"`
}

type Tag struct {
	ID       int64  `db:"id" json:"id"`
	Name     string `db:"name" json:"name"`
	ParentID *int64 `db:"parent_id" json:"parent_id"`
}

type Todo struct {
	ID            int64      `db:"id" json:"id"`
	Title         string     `db:"title" json:"title"`
	Score         int64      `db:"score" json:"score"`
	Amount        float64    `db:"amount" json:"amount"`
	Status        string     `db:"status" json:"status"`
	CreatedAt     *time.Time `db:"created_at" json:"created_at"`
	UpdatedAt     *time.Time `db:"updated_at" json:"updated_at"`
	Deadline      *time.Time `db:"deadline" json:"deadline"`
	Priority      string     `db:"priority" json:"priority"`
	Tags          string     `db:"tags" json:"tags"`
	Content       string     `db:"content" json:"content"`
	CreatedBy     string     `db:"created_by" json:"created_by"`
	AssigneeEmail string     `db:"assignee_email" json:"assignee_email"`
	DetailID      *int64     `db:"detail_id" json:"detail_id"`
	CategoryID    *int64     `db:"category_id" json:"category_id"`
}

type TodosOnGroup struct {
	TodoID     int64      `db:"todo_id" json:"todo_id"`
	GroupID    int64      `db:"group_id" json:"group_id"`
	AssignedAt *time.Time `db:"assigned_at" json:"assigned_at"`
}

type User struct {
	ID            string     `db:"id" json:"id"`
	Name          *string    `db:"name" json:"name"`
	Password      *string    `db:"password" json:"password"`
	Email         *string    `db:"email" json:"email"`
	Emailverified *time.Time `db:"emailverified" json:"emailverified"`
	Image         *string    `db:"image" json:"image"`
	Role          string     `db:"role" json:"role"`
}
