
# Choose the dialect among ['pgx', 'mysql', 'sqlite3']
DB_DRIVER = "sqlite3"

# mysql =>  user:password@tcp(host:port)/db?k=v
# pgx   =>  user:password@host:port/db?k=v
DB_DSN = "db.sqlite"

# target database name you choose , not needed for sqlite and pgx, only for mysql
DB_NAME = "db.sqlite"

# target tables used for stmt generation
TABLES = []

# Enable logger or not
LOG_ENABLED = true
	