DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS Tag;
DROP TABLE IF EXISTS Todo;
DROP TABLE IF EXISTS Detail;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS [Group];
DROP TABLE IF EXISTS TodosOnGroups;